### ISSUE TITLE
Uso do await no return

### ISSUE THREAD

**Issue by BlackCode7** [alexandersantosdev/FullStack-Week2.0-Larissa-Falc-o#1]
O uso do await no return é uma redundância o ESLint do vs code acusa como erro e não permite que a aplicação rode! 

só pra constar nas linhas 13, 21 e nas demais onde tem o comando await!

**Comment by alexandersantosdev** [comment]
Alterado. Grato pela análise!

**Comment by BlackCode7** [comment]
Valeu Alexandre, tmj!

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Alexander Roberto dos ***@***.***>
Enviado:segunda-feira, 31 de maio de 2021 19:07
Para: ***@***.***>
Cc:Anderson ***@***.***>; ***@***.***>
Assunto: Re: [alexandersantosdev/FullStack-Week2.0-Larissa-Falc-o] Uso do await no return (#1)


Alterado. Grato pela análise!
